version: "3"
services:
  naruto-meow:
    image: aarushgoyal/discord-bot
    env_file: .env
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

  # docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock v2tec/watchtower naruto-meow
