version: "3"
services:
  naruto-meow:
    image: aarushgoyal/discord-bot
    env_file: .env
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --debug --interval 30
