version: "3"
services:
  naruto-meow:
    image: aarushgoyal/discord-bot
    depends_on:
      - api
    env_file: .env
    restart: always
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 120
  api:
    image: aarushgoyal/narutomeow-api
    restart: always
    env_file: .env
    ports:
      - 8000:8000
  scraper:
    image: aarushgoyal/narutomeow-scraper
    restart: always
    depends_on:
      - api
    env_file: .env
